config/routes.rb
Eightbitbeer::Application.routes.draw do

  devise_for  :brewers, :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  resources :ingredients,
            :log_entries,
            :batches,
            :recipes

  resource :styleguide
  root :to => 'home#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_and_belongs_to_many :recipes
  has_and_belongs_to_many :steps

  validates_presence_of :name, :ingredient_type
  validates_uniqueness_of :name

  scope :ordered, order('name ASC')
  scope :grains, ordered.where(ingredient_type: 'Grains')
  scope :malts, ordered.where(ingredient_type: 'Malts')
  scope :hops, ordered.where(ingredient_type: 'Hops')
  scope :yeast, ordered.where(ingredient_type: 'Yeast')
  scope :other, ordered.where(ingredient_type: 'Other')

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :authenticate_brewer!, except: [:index, :show]

  def index
    @ingredients = Ingredient.all
    @grains = Ingredient.grains
    @malts  = Ingredient.malts
    @hops   = Ingredient.hops
    @yeast  = Ingredient.yeast
    @other  = Ingredient.other
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def create
    @ingredient = Ingredient.new(params[:ingredient])

    if @ingredient.save
      redirect_to ingredients_path, notice: 'Ingredient was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update_attributes(params[:ingredient])
      redirect_to ingredients_path, notice: 'Ingredient was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    redirect_to ingredients_url
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
  def ingredient_types
    return Array['Grains', 'Malts', 'Hops', 'Yeast', 'Other']
  end
end

app/views/ingredients/_form.html.haml
= form_for @ingredient do |f|
  -if @ingredient.errors.any?
    #error
      %h2= "#{pluralize(@ingredient.errors.count, "error")} prohibited this ingredient from being saved:"
      %ul
        - @ingredient.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name, class: 'h3'

  %ul.inline-input-list
    - ingredient_types.each do |type_name|
      %li
        %label
          = f.radio_button :ingredient_type, type_name
          = type_name

  .field
    = f.label :notes
    %br/
    = f.text_area :notes

  .actions
    = f.submit 'Save'

app/views/ingredients/_table.html.haml
%table
  %thead
    %tr
      %th Name
      %th Notes

      %th

  - ingredients.each do |ingredient|
    %tbody
      %tr
        %td= ingredient.name
        %td= ingredient.notes

        %td
          = link_to 'Edit', edit_ingredient_path(ingredient)
          |
          = link_to 'Destroy', ingredient, :confirm => 'Are you sure?', :method => :delete

app/views/ingredients/edit.html.haml
%h1 Editing ingredient

= render 'form'

= link_to 'Show', @ingredient
\|
= link_to 'Back', ingredients_path

app/views/ingredients/index.html.haml
%h1 Ingredients

.actions= link_to 'Add a new Ingredient', new_ingredient_path, class: 'button'

- unless @grains.empty?
  %h2= t('grains')
  = render 'table', ingredients: @grains

- unless @grains.empty?
  %h2= t('malts')
  = render 'table', ingredients: @malts

- unless @grains.empty?
  %h2= t('hops')
  = render 'table', ingredients: @hops

- unless @grains.empty?
  %h2= t('yeast')
  = render 'table', ingredients: @yeast

- unless @grains.empty?
  %h2= t('other')
  = render 'table', ingredients: @other

app/views/ingredients/new.html.haml
%h1 New ingredient

= render 'form'

= link_to 'Back', ingredients_path

app/views/ingredients/show.html.haml
%h1 Ingredients

%h2= @ingredient.name

.row
  .spans2.align-right
    %strong Type:
  .spans14= @ingredient.ingredient_type

.row
  .spans2.align-right
    %strong Notes:
  .spans14= @ingredient.notes

.row
  .spans14-offset2= link_to 'Edit', edit_ingredient_path(@ingredient)