config/routes.rb
Eightbitbeer::Application.routes.draw do

  devise_for  :brewers, :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  resources :ingredients,
            :log_entries,
            :batches,
            :recipes

  resource :styleguide
  root :to => 'home#index'

end

app/views/layouts/_dev.haml
.clear
.dev
  %p= params.inspect
  %p= current_brewer.inspect

app/views/layouts/_header.html.haml
%header
  .inner-content
    %h1= link_to t('brand_name'), root_path
    %nav
      - if brewer_signed_in?
        %ul.action-nav
          %li
            = link_to '+', new_batch_path
            = link_to 'Batches', batches_path
          %li
            = link_to '+', new_recipe_path
            = link_to 'Recipes', recipes_path
          %li
            = link_to '+', new_ingredient_path
            = link_to 'Ingredients', ingredients_path

          - if current_brewer.is_admin?
            %li= link_to 'Brewers', ''
            %li= link_to 'Admin', ''

      %ul.user-nav
        - if brewer_signed_in?
          %li= link_to 'Logout', destroy_brewer_session_path, :method => 'delete'
        - elsif where_i_am != new_brewer_session_path
          %li= link_to 'Login', new_brewer_session_path
      .clear

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title 8-Bit Brewing Co.

    %meta{content: 'yes', name: 'apple-mobile-web-app-capable'}
    %meta{content: 'black', name: 'apple-mobile-web-app-status-bar-style'}
    %meta{content: 'width = device-width, initial-scale = 1, maximum-scale = 1, user-scalable = yes', name: 'viewport'}

    %link{href:'http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,800', rel: 'stylesheet', type: 'text/css'}
    = stylesheet_link_tag 'application'
    = csrf_meta_tags

  %body
    .container
      = render '/layouts/header'
      .system
        - if notice
          .notice= notice
        - if alert
          .alert= alert
      #content
        = yield

      %footer
        .attribution &copy;2012 8-Bit Brewing Co. All rights reserved.

    .clear
    = javascript_include_tag 'application'

    - if brewer_signed_in? and current_brewer.is_admin?
      = render '/layouts/dev'